/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-container": "#3f465c",
              "on-tertiary": "#003915",
              "outline-variant": "#3e4850",
              "surface-bright": "#363a3b",
              "surface-container-high": "#272a2c",
              "inverse-surface": "#e0e3e5",
              "primary-container": "#24a1de",
              "on-secondary-container": "#adb4ce",
              "outline": "#88929b",
              "on-surface": "#e0e3e5",
              "surface-container-lowest": "#0b0f10",
              "surface-variant": "#323537",
              "tertiary-fixed": "#6bff8f",
              "tertiary-container": "#00af4f",
              "secondary-fixed-dim": "#bec6e0",
              "on-primary-fixed-variant": "#004c6d",
              "on-tertiary-fixed": "#002109",
              "secondary-fixed": "#dae2fd",
              "error-container": "#93000a",
              "tertiary": "#4ae176",
              "surface": "#101415",
              "surface-container": "#1d2022",
              "on-error-container": "#ffdad6",
              "on-primary": "#00344c",
              "primary": "#86cfff",
              "on-primary-fixed": "#001e2e",
              "background": "#101415",
              "tertiary-fixed-dim": "#4ae176",
              "surface-dim": "#101415",
              "on-tertiary-container": "#003915",
              "on-background": "#e0e3e5",
              "surface-container-low": "#191c1e",
              "on-secondary": "#283044",
              "error": "#ffb4ab",
              "on-error": "#690005",
              "on-primary-container": "#00344c",
              "on-secondary-fixed": "#131b2e",
              "inverse-on-surface": "#2d3133",
              "on-surface-variant": "#bec8d1",
              "on-secondary-fixed-variant": "#3f465c",
              "primary-fixed-dim": "#86cfff",
              "secondary": "#bec6e0",
              "inverse-primary": "#00658f",
              "primary-fixed": "#c8e6ff",
              "surface-container-highest": "#323537",
              "on-tertiary-fixed-variant": "#005321",
              "surface-tint": "#86cfff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "safe-area": "16px",
              "unit": "4px",
              "sm": "8px",
              "lg": "24px",
              "gutter": "12px",
              "md": "16px",
              "xs": "4px",
              "xl": "40px"
      },
      "fontFamily": {
              "headline-md": ["Space Grotesk", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "headline-lg": ["Space Grotesk", "sans-serif"],
              "code-snippet": ["Inter", "monospace"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "label-md": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "code-snippet": ["13px", {"lineHeight": "1.4", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
